# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_quizDialog.ui'
#
# Created: Tue Aug 16 04:40:39 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_quizDialog(object):
    def setupUi(self, quizDialog):
        quizDialog.setObjectName("quizDialog")
        quizDialog.resize(540, 600)
        quizDialog.setMinimumSize(QtCore.QSize(540, 600))
        quizDialog.setMaximumSize(QtCore.QSize(540, 600))
        self.correctCount = QtGui.QLabel(quizDialog)
        self.correctCount.setGeometry(QtCore.QRect(69, 550, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.correctCount.setFont(font)
        self.correctCount.setAlignment(QtCore.Qt.AlignCenter)
        self.correctCount.setObjectName("correctCount")
        self.btn1 = QtGui.QPushButton(quizDialog)
        self.btn1.setGeometry(QtCore.QRect(40, 520, 110, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn1.sizePolicy().hasHeightForWidth())
        self.btn1.setSizePolicy(sizePolicy)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtGui.QPushButton(quizDialog)
        self.btn2.setGeometry(QtCore.QRect(152, 520, 110, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn2.sizePolicy().hasHeightForWidth())
        self.btn2.setSizePolicy(sizePolicy)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtGui.QPushButton(quizDialog)
        self.btn3.setGeometry(QtCore.QRect(264, 520, 110, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn3.sizePolicy().hasHeightForWidth())
        self.btn3.setSizePolicy(sizePolicy)
        self.btn3.setObjectName("btn3")
        self.btn4 = QtGui.QPushButton(quizDialog)
        self.btn4.setGeometry(QtCore.QRect(375, 520, 110, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn4.sizePolicy().hasHeightForWidth())
        self.btn4.setSizePolicy(sizePolicy)
        self.btn4.setObjectName("btn4")
        self.frame = QtGui.QFrame(quizDialog)
        self.frame.setGeometry(QtCore.QRect(20, 9, 500, 500))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.imgLabel = QtGui.QLabel(self.frame)
        self.imgLabel.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.imgLabel.setMaximumSize(QtCore.QSize(500, 500))
        self.imgLabel.setText("")
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setObjectName("imgLabel")
        self.wrongCount = QtGui.QLabel(quizDialog)
        self.wrongCount.setGeometry(QtCore.QRect(420, 550, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wrongCount.setFont(font)
        self.wrongCount.setAlignment(QtCore.Qt.AlignCenter)
        self.wrongCount.setObjectName("wrongCount")
        self.totalCount = QtGui.QLabel(quizDialog)
        self.totalCount.setGeometry(QtCore.QRect(210, 550, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalCount.setFont(font)
        self.totalCount.setAlignment(QtCore.Qt.AlignCenter)
        self.totalCount.setObjectName("totalCount")
        self.wrongLabel = QtGui.QLabel(quizDialog)
        self.wrongLabel.setGeometry(QtCore.QRect(450, 550, 29, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrongLabel.sizePolicy().hasHeightForWidth())
        self.wrongLabel.setSizePolicy(sizePolicy)
        self.wrongLabel.setText("")
        self.wrongLabel.setPixmap(QtGui.QPixmap("imgs/icons/qdlg_wrong.png"))
        self.wrongLabel.setObjectName("wrongLabel")
        self.correctLabe = QtGui.QLabel(quizDialog)
        self.correctLabe.setGeometry(QtCore.QRect(40, 550, 29, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correctLabe.sizePolicy().hasHeightForWidth())
        self.correctLabe.setSizePolicy(sizePolicy)
        self.correctLabe.setText("")
        self.correctLabe.setPixmap(QtGui.QPixmap("imgs/icons/qdlg_correct.png"))
        self.correctLabe.setObjectName("correctLabe")

        self.retranslateUi(quizDialog)
        QtCore.QMetaObject.connectSlotsByName(quizDialog)

    def retranslateUi(self, quizDialog):
        quizDialog.setWindowTitle(QtGui.QApplication.translate("quizDialog", "Ganbatte!", None, QtGui.QApplication.UnicodeUTF8))
        self.correctCount.setText(QtGui.QApplication.translate("quizDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btn1.setText(QtGui.QApplication.translate("quizDialog", "Ka", None, QtGui.QApplication.UnicodeUTF8))
        self.btn2.setText(QtGui.QApplication.translate("quizDialog", "Ri", None, QtGui.QApplication.UnicodeUTF8))
        self.btn3.setText(QtGui.QApplication.translate("quizDialog", "So", None, QtGui.QApplication.UnicodeUTF8))
        self.btn4.setText(QtGui.QApplication.translate("quizDialog", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.wrongCount.setText(QtGui.QApplication.translate("quizDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalCount.setText(QtGui.QApplication.translate("quizDialog", "0 / 5", None, QtGui.QApplication.UnicodeUTF8))

