# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_romanize.ui'
#
# Created: Fri Aug 26 00:33:11 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_romanizeDialog(object):
    def setupUi(self, romanizeDialog):
        romanizeDialog.setObjectName("romanizeDialog")
        romanizeDialog.resize(700, 200)
        romanizeDialog.setMinimumSize(QtCore.QSize(700, 200))
        romanizeDialog.setMaximumSize(QtCore.QSize(700, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/icons/m_romanize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        romanizeDialog.setWindowIcon(icon)
        self.label = QtGui.QLabel(romanizeDialog)
        self.label.setGeometry(QtCore.QRect(0, -4, 711, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/imgs/icons/background.png"))
        self.label.setObjectName("label")
        self.groupBox = QtGui.QGroupBox(romanizeDialog)
        self.groupBox.setGeometry(QtCore.QRect(-10, -10, 711, 211))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.harf1 = QtGui.QLabel(self.groupBox)
        self.harf1.setText("")
        self.harf1.setObjectName("harf1")
        self.horizontalLayout.addWidget(self.harf1)
        self.harf2 = QtGui.QLabel(self.groupBox)
        self.harf2.setText("")
        self.harf2.setObjectName("harf2")
        self.horizontalLayout.addWidget(self.harf2)
        self.harf3 = QtGui.QLabel(self.groupBox)
        self.harf3.setText("")
        self.harf3.setObjectName("harf3")
        self.horizontalLayout.addWidget(self.harf3)
        self.harf4 = QtGui.QLabel(self.groupBox)
        self.harf4.setText("")
        self.harf4.setObjectName("harf4")
        self.horizontalLayout.addWidget(self.harf4)
        self.harf5 = QtGui.QLabel(self.groupBox)
        self.harf5.setText("")
        self.harf5.setObjectName("harf5")
        self.horizontalLayout.addWidget(self.harf5)
        self.harf6 = QtGui.QLabel(self.groupBox)
        self.harf6.setText("")
        self.harf6.setObjectName("harf6")
        self.horizontalLayout.addWidget(self.harf6)
        self.harf7 = QtGui.QLabel(self.groupBox)
        self.harf7.setText("")
        self.harf7.setObjectName("harf7")
        self.horizontalLayout.addWidget(self.harf7)
        self.harf8 = QtGui.QLabel(self.groupBox)
        self.harf8.setText("")
        self.harf8.setObjectName("harf8")
        self.horizontalLayout.addWidget(self.harf8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.quitButton = QtGui.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/icons/d_quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon1)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout.addWidget(self.quitButton, 2, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 2)
        self.checkButton = QtGui.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/icons/d_added.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkButton.setIcon(icon2)
        self.checkButton.setObjectName("checkButton")
        self.gridLayout.addWidget(self.checkButton, 2, 0, 1, 1)

        self.retranslateUi(romanizeDialog)
        QtCore.QObject.connect(self.quitButton, QtCore.SIGNAL("clicked()"), romanizeDialog.close)
        QtCore.QMetaObject.connectSlotsByName(romanizeDialog)
        romanizeDialog.setTabOrder(self.lineEdit, self.checkButton)
        romanizeDialog.setTabOrder(self.checkButton, self.quitButton)

    def retranslateUi(self, romanizeDialog):
        romanizeDialog.setWindowTitle(QtGui.QApplication.translate("romanizeDialog", "Romanize The Given Word [under-development]", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("romanizeDialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("romanizeDialog", "romanize it here and press enter", None, QtGui.QApplication.UnicodeUTF8))
        self.checkButton.setText(QtGui.QApplication.translate("romanizeDialog", "Check", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
